[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Veeam"
authors = [{name = "Eric W", email = "eric@hker.site"}]
dynamic = ["version", "description"]
